# app/services/comprobante_formatter.py
from app.models.comprobante import Comprobante

class ComprobanteFormatter:
    @staticmethod
    def format_comprobante(
        filename: str,
        size: int,
        content_type: str,
        text_content: str,
        qr_content: str | None,
        diagnostic_messages: list[str],
        punto_venta: str,
        numero_comprobante: str,
        fecha_emision: str | None,
        importe_total: str,
        periodo_facturado_desde: str | None,
        periodo_facturado_hasta: str | None,
        cuit_emisor: str,
        razon_social_emisor: str | None,
        domicilio_comercial_emisor: str | None,
        condicion_iva_emisor: str | None,
        cuit_receptor: str | None,
        razon_social_receptor: str | None,
        domicilio_comercial_receptor: str | None,
        condicion_iva_receptor: str | None,
        subtotal: str | None,
        bonificacion_porcentaje: str | None,
        bonificacion_importe: str | None,
        subtotal_con_bonificacion: str | None,
        importe_otros_tributos: str | None,
        profesion_oficio: str | None,
        cae_numero: str | None,
        cae_fecha_vencimiento: str | None,
        cantidad_copias: int,
        es_comprobante_valido: bool,
    ) -> Comprobante:
        return Comprobante(
            filename=filename,
            size=size,
            content_type=content_type,
            text_content=text_content,
            qr_content=qr_content,
            diagnostic_messages=diagnostic_messages,
            punto_venta=punto_venta,
            numero_comprobante=numero_comprobante,
            fecha_emision=fecha_emision,
            importe_total=importe_total,
            periodo_facturado_desde=periodo_facturado_desde,
            periodo_facturado_hasta=periodo_facturado_hasta,
            cuit_emisor=cuit_emisor,
            razon_social_emisor=razon_social_emisor,
            domicilio_comercial_emisor=domicilio_comercial_emisor,
            condicion_iva_emisor=condicion_iva_emisor,
            cuit_receptor=cuit_receptor,
            razon_social_receptor=razon_social_receptor,
            domicilio_comercial_receptor=domicilio_comercial_receptor,
            condicion_iva_receptor=condicion_iva_receptor,
            subtotal=subtotal,
            bonificacion_porcentaje=bonificacion_porcentaje,
            bonificacion_importe=bonificacion_importe,
            subtotal_con_bonificacion=subtotal_con_bonificacion,
            importe_otros_tributos=importe_otros_tributos,
            profesion_oficio=profesion_oficio,
            cae_numero=cae_numero,
            cae_fecha_vencimiento=cae_fecha_vencimiento,
            cantidad_copias=cantidad_copias,
            es_comprobante_valido=es_comprobante_valido,
        )